version: "3.8"
services: 
  app: 
    build: .
    volumes: 
      - .:/django
    ports: 
      - 8000:8000
    image: app:django
    container_name: django_container
    command: python3 MyProject/manage.py runserver 0.0.0.0:8000
    # let current service of app depends on db service, so that 
    # can be created first
    depends_on: 
      - db
  db:
    image: mysql:5.7
    environment: 
      MYSQL_DATABASE: 'django-app-db'
      MYSQL_ALLOW_EMPTY_PASSWORD: 'yes'
    volumes: 
      - ./data/mysql/db:/var/lib/mysql
